### ISSUE TITLE
What about folders?

### ISSUE THREAD

**Issue by vonagam** [PotterDai/vscode-unitymeta#1]
Hi, thanks for this extension.

I see that it does not react to folder changes like it does to file ones. (Because of [watcher's pattern](https://github.com/PotterDai/vscode-unitymeta/blob/94c6316ad9a6d1612440528d491d20f4f70b27e5/src/metafilewatcher.ts#L13))

Is this intentional because of some problems or can they be added to watchlist (as they too have meta files and produce warnings in unity console)?

**Comment by potterdai** [comment]
Thanks for bringing it up. It has just been fixed.
