### ISSUE TITLE
Moving files does not move the associated meta file

### ISSUE THREAD

**Issue by lazlo-bonin** [PotterDai/vscode-unitymeta#2]
From what I understand, this extension only supports renaming, but not moving, right?

It would be great if file move operations carried the meta file along as well. Right now they can easily break since the default settings for code workspaces hide the */**.meta pattern,

**Comment by potterdai** [comment]
Hi, actually it should support moving. If you tried it and the moving is not working, then there might be a bug...
I just tried it on my laptop, and it seems moving is working properly.
My environment is MacOS Catalina, Unity3d 2019.3 beta6
